stages:
  - test

variables:
  TF_VERSION: 1.6.5
  GOTESTSUM_VERSION: 1.11.0

format:test:
  image: golang:1.21.4-bookworm
  script:
    - export GOFMT_OUTPUT="$(gofmt -l test)"
    - echo "$GOFMT_OUTPUT"
    - "[ $(echo -n $GOFMT_OUTPUT | wc -l) -eq 0 ]"

lint:test:
  image: golangci/golangci-lint:v1.55.2
  script:
    - cd test
    - golangci-lint run --timeout=5m ./...

# Requires PROXMOX_VE_API_TOKEN variables of the form:
#   user@realm!token=secret
# For example:
#   user@pve!token=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
test:terraform:
  stage: test
  image: golang:1.21.4-bookworm
  before_script:
    - apt-get update
    - apt-get install --yes unzip
    - wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    - unzip /tmp/terraform.zip
    - mv terraform /usr/local/bin
  script:
    - cd test
    - go test ./...

lint:terraform:
  stage: test
  image: ghcr.io/terraform-linters/tflint:v0.49.0
  script:
    - tflint --chdir=modules/machine
    - tflint --chdir=examples/debian-machine
    - tflint --chdir=examples/alpine-machine

format:terraform:
  stage: test
  image: debian:bookworm-slim
  before_script:
    - apt-get update
    - apt-get install --yes wget unzip
    - wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
    - unzip /tmp/terraform.zip
    - mv terraform /usr/local/bin
  script:
    - terraform fmt -check -recursive .
