stages:
  - test

format-test:
  image: golang:1.18.2
  script:
    - export GOFMT_OUTPUT="$(gofmt -l test)"
    - echo "$GOFMT_OUTPUT"
    - '[ $(echo -n $GOFMT_OUTPUT | wc -l) -eq 0 ]'

lint-test:
  image: golang:1.18.2
  script:
    - cd test
    # Install golangci-lint.
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.45.2
    - bin/golangci-lint run

# Requires PM_API_TOKEN_ID, PM_API_TOKEN_SECRET variables.
test-terraform:
  stage: test
  needs:
    - format-test
    - lint-test
  image: golang:1.18.2
  script:
    - apt update
    - apt install unzip
    - wget -O /tmp/terraform.zip https://releases.hashicorp.com/terraform/1.2.5/terraform_1.2.5_linux_amd64.zip
    - unzip /tmp/terraform.zip
    - mv terraform /usr/local/bin
    - wget -O /tmp/gotestsum.tar.gz https://github.com/gotestyourself/gotestsum/releases/download/v1.8.1/gotestsum_1.8.1_linux_amd64.tar.gz
    - tar -xzf /tmp/gotestsum.tar.gz
    - mv gotestsum /usr/local/bin
    - cd test
    # Use gotestsum to generate a JUnit-like report.
    - gotestsum --junitfile report.xml --format testname
  artifacts:
    when: always
    reports:
      junit: test/report.xml

lint-terraform:
  stage: test
  image: ghcr.io/terraform-linters/tflint:v0.38.1
  script:
    - tflint --module modules/machine
    - tflint examples/machine

format-terraform:
  stage: test
  image: docker.houseofkummer.com/homelab/dockops:0.6.0
  script:
    - terraform fmt -check -recursive .
